"""
FK94 Security Platform - PDF Report Generator
"""
import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)

from app.models.schemas import AuditResult, RiskLevel


class PDFReportService:
    """Generate professional PDF security reports"""

    def __init__(self):
        self.styles = self._create_styles()

    def _create_styles(self):
        """Create custom styles for the report"""
        base = getSampleStyleSheet()

        return {
            "title": ParagraphStyle(
                "Title",
                parent=base["Heading1"],
                fontSize=24,
                alignment=TA_CENTER,
                fontName="Helvetica-Bold",
                textColor=colors.HexColor("#1a1a2e"),
                spaceAfter=12,
            ),
            "subtitle": ParagraphStyle(
                "Subtitle",
                parent=base["Normal"],
                fontSize=12,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#666666"),
                spaceAfter=20,
            ),
            "section": ParagraphStyle(
                "Section",
                parent=base["Heading2"],
                fontSize=14,
                fontName="Helvetica-Bold",
                textColor=colors.HexColor("#1a365d"),
                spaceBefore=20,
                spaceAfter=10,
            ),
            "body": ParagraphStyle(
                "Body",
                parent=base["Normal"],
                fontSize=10,
                alignment=TA_JUSTIFY,
                leading=14,
                spaceAfter=8,
            ),
            "score_large": ParagraphStyle(
                "ScoreLarge",
                parent=base["Normal"],
                fontSize=48,
                alignment=TA_CENTER,
                fontName="Helvetica-Bold",
            ),
            "recommendation": ParagraphStyle(
                "Recommendation",
                parent=base["Normal"],
                fontSize=10,
                leftIndent=20,
                spaceAfter=6,
            ),
        }

    def generate_report(self, audit: AuditResult) -> bytes:
        """Generate PDF report from audit results"""

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )

        story = []

        # === HEADER ===
        story.append(Paragraph("🛡️ SECURITY AUDIT REPORT", self.styles["title"]))
        story.append(Paragraph(
            f"Generated by FK94 Security | {audit.timestamp.strftime('%Y-%m-%d %H:%M')}",
            self.styles["subtitle"]
        ))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a365d")))
        story.append(Spacer(1, 20))

        # === SECURITY SCORE ===
        score = audit.security_score
        score_color = self._get_score_color(score.risk_level)

        story.append(Paragraph("SECURITY SCORE", self.styles["section"]))

        # Score display
        score_style = ParagraphStyle(
            "ScoreDisplay",
            parent=self.styles["score_large"],
            textColor=score_color
        )
        story.append(Paragraph(f"{score.score}/100", score_style))
        story.append(Paragraph(
            f"Risk Level: {score.risk_level.value.upper()}",
            ParagraphStyle("Risk", alignment=TA_CENTER, fontSize=14, textColor=score_color)
        ))
        story.append(Spacer(1, 10))

        # Score breakdown table
        breakdown_data = [
            ["Category", "Score", "Max"],
            ["Breach Exposure", str(score.breakdown.get("breaches", 0)), "35"],
            ["Password Security", str(score.breakdown.get("passwords", 0)), "30"],
            ["OSINT Exposure", str(score.breakdown.get("osint", 0)), "20"],
            ["Configuration", str(score.breakdown.get("configuration", 0)), "15"],
        ]
        breakdown_table = Table(breakdown_data, colWidths=[3*inch, 1.5*inch, 1.5*inch])
        breakdown_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a365d")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(breakdown_table)
        story.append(Spacer(1, 20))

        # === ISSUES SUMMARY ===
        story.append(Paragraph("ISSUES FOUND", self.styles["section"]))

        issues_data = [
            ["🔴 Critical", str(score.issues_critical)],
            ["🟠 High", str(score.issues_high)],
            ["🟡 Medium", str(score.issues_medium)],
            ["🟢 Low", str(score.issues_low)],
        ]
        issues_table = Table(issues_data, colWidths=[4*inch, 2*inch])
        issues_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (0, -1), "LEFT"),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
            ("FONTSIZE", (0, 0), (-1, -1), 11),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(issues_table)
        story.append(Spacer(1, 20))

        # === BREACH DETAILS ===
        if audit.breach_check and audit.breach_check.breached:
            story.append(Paragraph("DATA BREACHES", self.styles["section"]))
            story.append(Paragraph(
                f"Your email <b>{audit.email}</b> was found in <b>{audit.breach_check.breach_count}</b> data breaches:",
                self.styles["body"]
            ))

            for breach in audit.breach_check.breaches[:10]:  # Limit to 10
                breach_text = f"<b>{breach.name}</b>"
                if breach.date:
                    breach_text += f" ({breach.date})"
                if breach.data_types:
                    breach_text += f" - Exposed: {', '.join(breach.data_types[:5])}"
                story.append(Paragraph(f"• {breach_text}", self.styles["recommendation"]))

            story.append(Spacer(1, 15))

        # === RECOMMENDATIONS ===
        story.append(PageBreak())
        story.append(Paragraph("RECOMMENDATIONS", self.styles["section"]))
        story.append(Paragraph(
            "Based on your audit results, here are prioritized actions to improve your security:",
            self.styles["body"]
        ))

        for i, rec in enumerate(audit.recommendations, 1):
            story.append(Paragraph(f"{i}. {rec}", self.styles["recommendation"]))

        story.append(Spacer(1, 20))

        # === AI ANALYSIS ===
        if audit.ai_analysis:
            story.append(Paragraph("AI SECURITY ANALYSIS", self.styles["section"]))
            # Split AI analysis into paragraphs
            for para in audit.ai_analysis.split("\n\n"):
                if para.strip():
                    story.append(Paragraph(para.strip(), self.styles["body"]))

        # === FOOTER ===
        story.append(Spacer(1, 30))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            "This report was generated by FK94 Security Platform. "
            "For more information, visit https://fk94security.com",
            ParagraphStyle("Footer", alignment=TA_CENTER, fontSize=8, textColor=colors.gray)
        ))
        story.append(Paragraph(
            f"Report ID: {audit.id} | Generated: {audit.timestamp.isoformat()}",
            ParagraphStyle("FooterID", alignment=TA_CENTER, fontSize=8, textColor=colors.gray)
        ))

        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    def _get_score_color(self, risk_level: RiskLevel) -> colors.Color:
        """Get color based on risk level"""
        color_map = {
            RiskLevel.CRITICAL: colors.HexColor("#dc2626"),
            RiskLevel.HIGH: colors.HexColor("#ea580c"),
            RiskLevel.MEDIUM: colors.HexColor("#ca8a04"),
            RiskLevel.LOW: colors.HexColor("#16a34a"),
            RiskLevel.SAFE: colors.HexColor("#059669"),
        }
        return color_map.get(risk_level, colors.black)


# Singleton
pdf_service = PDFReportService()
